name: Setup
description: ''

runs:
  using: composite
  steps:
    - name: Setup toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        components: clippy
        override: true

    - name: Setup sqlx-cli
      uses: baptiste0928/cargo-install@v2
      with:
        crate: sqlx-cli
