[workspace]
resolver = "2"
members = ["maiq-cli", "maiq-parser"]

[workspace.package]
edition = "2021"

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
incremental = false
opt-level = "s"
