[package]
name = "maiq-bot"
version = { workspace = true }
repository = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }
license = { workspace = true }

[dependencies]
tokio = { version = "^1.32", features = ["rt-multi-thread", "macros"] }
teloxide = { version = "^0.12", default-features = false, features = [
  "cache-me",
  "macros",
  "teloxide-macros",
  "bincode",
  "bincode-serializer",
  "rustls",
] }
maiq-db = { path = "../maiq-db" }
maiq-parser-next = { path = "../maiq-parser" }

log = "^0.4"
dotenvy = "^0.15"

fastrand = "^2.0"
bincode = "^1.3"
color-eyre = "^0.6"
env_logger = "^0.10"
serde = { version = "^1.0", features = ["derive"] }
build-info = "^0.0"
anyhow = "^1.0"
include_dir = "^0.7"

[dev-dependencies]
rstest = "^0.18"

[build-dependencies]
pulldown-cmark = { version = "^0.9", features = ["simd"] }
build-info-build = { version = "^0.0", default-features = false }
walkdir = "^2.4"
