name: Run lint & tests

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

env:
  CARGO_TERM_COLOR: always

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.SQLX_DATABASE }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: clippy
          override: true

      - name: Setup sqlx-cli
        uses: baptiste0928/cargo-install@v2
        with:
          crate: sqlx-cli

      - name: Reset database
        run: cargo sqlx database reset --source maiq-db/migrations -y -D ${{ secrets.SQLX_DATABASE }}

      - name: Linting
        run: cargo clippy --all-features --no-deps -- -Dwarnings

      - name: Testing
        run: cargo test --package maiq-parser-next --tests
