name: Run lint & tests

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

env:
  DATABASE_URL: ${{ secrets.SQLX_DATABASE }}
  CARGO_TERM_COLOR: always

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: ./.github/actions/setup
        with:
          db-url: ${{ secrets.SQLX_DATABASE }}

      - name: Linting
        run: cargo clippy --all-features --no-deps

  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: ./.github/actions/setup

      - name: Testing
        run: cargo test --package maiq-parser-next --tests
