name: Run tests

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set toolchain
        run: rustup override set nightly
      - name: Build
        run: cargo build
      - name: Tests
        run: cargo test --package maiq-parser-next --lib
