name: Lint

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: clippy

      - name: Setup sqlx-cli
        uses: baptiste0928/cargo-install@v2
        with:
          crate: sqlx-cli

      - name: Linting
        run: cargo clippy --all-features --no-deps

  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: clippy

      - name: Setup sqlx-cli
        uses: baptiste0928/cargo-install@v2
        with:
          crate: sqlx-cli

      - name: Testing
        run: cargo test --workspace --no-fail-fast
