name: Lint & Test

on:
  push:
    branches: ['master', 'develop']
  pull_request:
    branches: ['master', 'develop']

env:
  SQLX_OFFLINE: 1
  CARGO_TERM_COLOR: always

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup toolchain
        uses: ructions/toolchain@v1
        with:
          override: true
          toolchain: stable
          components: clippy

      - name: Linting
        run: cargo clippy --all-features --no-deps

  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup toolchain
        uses: ructions/toolchain@v1
        with:
          override: true
          toolchain: stable

      - name: Testing
        run: cargo test --workspace --no-fail-fast
