name: Run lint & tests

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: clippy

      - name: Linting
        run: cargo clippy --no-deps -- -Dwarnings

      - name: Testing
        run: cargo test --package maiq-parser-next --tests
